### ISSUE TITLE
How to obtain active post id easily? I think the README may needs update

### ISSUE THREAD

**Issue by fish1968** [tideillusion/lgulife#1]
I find the README document a little out dated. Since a few weeks ago, lgulife has made an modification on its style of post URL. 
Although the structure of forming a valid URL hasn't changed too much, except that the post id is not a digital number anymore. It has been transformed from a readable number into a sequence of HEX codes in a random form. Take a recent hot post for e.g. [酸鸡无能狂怒](https://www.longgulife.com/p/a2cd858d6ad88ff8e8227893ba9c37e01218bb53/) Its working post id is  a2cd858d6ad88ff8e8227893ba9c37e01218bb53, which is crazy, not something that I could find a pattern with😥.
Luckily, your library is still one hundred percent OK as long as the ID given is proper.
```
>>> c = lgulife.buy("a2cd858d6ad88ff8e8227893ba9c37e01218bb53")
>>> c.comment
{'55848': {'comment_id': '55848', 'date': '26分钟前', 'down': 0, 'hot': False, 'images': [], 'name': '飞翔的抽屉', 'reply_to': None, 'text': 'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh', 'up': 0, 'user_id': None}, '55849': {'comment_id': '55849', 'date': '26分钟前', 'down': 0, 'hot': False, 'images': [], 'name': '飞翔的抽屉', 'reply_to': None, 'text': '笑死我了', 'up': 0, 'user_id': None}, '55851': {'comment_id': '55851', 'date': '17分钟前', 'down': 0, 'hot': False, 'images': [], 'name': '睡不着的酸菜鱼', 'reply_to': None, 'text': '笑死了，我也酸了哈哈哈', 'up': 0, 'user_id': None}, '55853': {'comment_id': '55853', 'date': '5分钟前', 'down': 0, 'hot': False, 'images': [], 'name': '有腹肌的水煮鱼', 'reply_to': None, 'text': '尊重他努力的结果，但他天天说自己不卷，没学上了的言论属实是....', 'up': 3, 'user_id': None}, '55854': {'comment_id': '55854', 'date': '刚刚', 'down': 0, 'hot': False, 'images': [], 'name': '侠义非凡的绿豆', 'reply_to': None, 'text': '哈哈哈哈哈哈哈哈哈哈哈', 'up': 0, 'user_id': None}}
```

However, this change of URL style makes scrawling job much more difficult. Obtaining recent days' posts, and do analysis is not as easy as it was.
I want to know, whether you know some ways to by pass this RANDOM HEX NUMBER BARRIER and make life easier one more time? 
Thanks.

**Comment by tideillusion** [comment]
Hi Fish1968, I also noticed the change of post id on LGULife. I guess that LGULife applied this change to protect their posts from being easiliy crawled and hide some deleted posts from newbie crawler-writers (if the pattern of post id is obvious, people easily notice that some posts are deleted).

My library still works because it does not rely on the pattern of post ids. Instead, the crawler behind it obtains the list of post ids directly from the contents page (e.g. https://www.longgulife.com/bbs/anonymity/?page=1). 

You may compare old and new post ids of the same posts and try to find the new pattern (I do not recommend that because the new post ids may be completely randomly generated), or do analysis without using post id as a feature.

Hope this will help 😊

**Comment by tideillusion** [comment]
BTW, the `view` function in the latest version actually receives three parameters: limit, start, end. You can look into the source code to find out how they work. Recently I am busy with my new work and have no time to update README.

If you figure out the usage of new `view`, PR/MR on README is welcomed.

**Comment by fish1968** [comment]
Great explanations. Thanks a lot.
Actually, I have just moved on doing python scrawling stuffs, and am still not very familiar with these things, but I will definitely find some time to look in your code, and hope I could figure it out. HaHa.
Thanks for your good work, and hope you are doing a good life.
Many thanks.😘
